name: ğŸš€ 1. Deploy to Master

on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: ğŸ‰ Deploy to Master
    runs-on: ubuntu-latest
    environment: master

    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v2.3.2

      - name: ğŸ§© Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: ğŸ§° Install Composer
        run: |
          sudo apt-get update
          sudo apt-get install -y composer

      - name: âœ… Validate Composer configuration
        run: composer validate

      - name: ğŸ“¦ Install Dependencies
        run: composer install --no-ansi --no-interaction --prefer-dist --verbose

      - name: ğŸ“‚ Sync files to Staging
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.swingersnest.com
          username: u756937133.swingersnest
          password: AAaa11@@AAopen2code.com
          server-dir: /
